name: Generate Animations

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: "0 */6 * * *" # Runs on the 0, 6, 12 and 18th hour.
  workflow_dispatch:

jobs:
  build:
    permissions:
      contents: write
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Create dist directory
        run: mkdir -p dist

      - name: Generate snake animation
        uses: Platane/snk@v3.1.0
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/grid-snake.svg
            dist/grid-snake-dark.svg?palette=github-dark
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate pacman animation
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          mkdir -p dist
          npm install -g pacman-contribution-graph
          pacman-contribution-graph --platform github --username ${{ github.repository_owner }} --gameTheme github --output dist/pacman-contribution-graph.svg
          pacman-contribution-graph --platform github --username ${{ github.repository_owner }} --gameTheme github-dark --output dist/pacman-contribution-graph-dark.svg

      - name: Generate gitartwork
        uses: jasineri/gitartwork@v1
        with:
          user_name: ${{ github.repository_owner }}
          text: HUNG!

      - name: Move gitartwork.svg to dist
        run: mv gitartwork.svg dist/

      - name: Push animations to output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
